# Site settings
title: developia.info | another developer stories repository 
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://developia.info"
author:
  name: "Manu Garcia"
  email: "manu@developia.info"
  url: "http://developia.info"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
